version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/dbm-app"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/dbm-script-lib"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/dbm-js-vm"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/dbm-web-resources"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/DbmSolution"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
