export const DOCUMENT_NODE_ID = 'document:root';
export const PACKAGE_NODE_ID = 'section:package';
export const PROCESS_NODE_ID = 'section:process';
export const PROCESS_ACTORS_NODE_ID = 'collection:process:actors';
export const PROCESS_VARIABLES_NODE_ID = 'collection:process:variables';
export const PROCESS_STAGES_NODE_ID = 'collection:process:stages';
export const PROCESS_TRANSITIONS_NODE_ID = 'collection:process:transitions';
export const PROCESS_OUTCOMES_NODE_ID = 'collection:process:outcomes';
export const FORMS_NODE_ID = 'section:forms';
export const METADATA_NODE_ID = 'section:metadata';
export const METADATA_ENTITIES_NODE_ID = 'collection:metadata:entities';
export const METADATA_RELATIONSHIPS_NODE_ID = 'collection:metadata:relationships';
export const RULES_NODE_ID = 'section:rules';
export const RUNTIME_NODE_ID = 'section:runtime';
export const RUNTIME_CAPABILITIES_NODE_ID = 'collection:runtime:capabilities';
export const RUNTIME_REQUEST_CONTRACT_NODE_ID = 'runtime:request-contract';
export const RUNTIME_RESULT_CONTRACT_NODE_ID = 'runtime:result-contract';
export const RUNTIME_OWNERSHIP_NODE_ID = 'runtime:ownership';
export const ARTIFACTS_NODE_ID = 'section:artifacts';

export const actorNodeId = (id: string): string => `actor:${id}`;
export const variableNodeId = (id: string): string => `variable:${id}`;
export const stageNodeId = (id: string): string => `stage:${id}`;
export const transitionNodeId = (id: string): string => `transition:${id}`;
export const outcomeNodeId = (id: string): string => `outcome:${id}`;
export const formNodeId = (id: string): string => `form:${id}`;
export const formLayoutNodeId = (formId: string): string => `layout:${formId}`;
export const formElementsNodeId = (formId: string): string => `collection:form:${formId}:elements`;
export const regionNodeId = (formId: string, regionId: string): string => `region:${formId}:${regionId}`;
export const elementNodeId = (formId: string, elementId: string): string => `element:${formId}:${elementId}`;
export const entityNodeId = (id: string): string => `entity:${id}`;
export const entityFieldsNodeId = (entityId: string): string => `collection:entity:${entityId}:fields`;
export const fieldNodeId = (entityId: string, fieldId: string): string => `field:${entityId}:${fieldId}`;
export const relationshipNodeId = (id: string): string => `relationship:${id}`;
export const ruleNodeId = (id: string): string => `rule:${id}`;
export const artifactNodeId = (id: string): string => `artifact:${id}`;
